debug = false

[db_config]
runtime_path = "/tmp/vds/runtime_path"
busy_timeout = "10 seconds"
pool_size = 16

[downloader_config]
concurrent_downloads = 8
content_path = "/tmp/vds/content_path"
remote_server = "s3://your-bucket-name"
update_interval = "20 seconds"

[downloader_config.retry_params]
initial_backoff = "5 seconds"
backoff_factor = 1.5
max_backoff = "2 hours"

[http_config]
listen_address = "127.0.0.1"
listen_port = 8080

[aws_config]
access_key_id = "your-access-key-id"
secret_access_key = "your-secret-access-key"
endpoint_url = "https://your-endpoint-url.com"
force_path_style = true # Use with non-aws endpoints
region = "us-east-1"
