debug = true

[db_config]
runtime_path = "/tmp/vds/runtime_path"
busy_timeout = "10 seconds"

[downloader_config]
concurrent_downloads = 8
content_path = "/tmp/vds/content_path"
remote_server = "/tmp/vds/fake_remote_server"
update_interval = "20 seconds"

[downloader_config.retry_params]
initial_backoff = "5 seconds"
backoff_factor = 1.5
max_backoff = "2 hours"

[http_config]
listen_address = "127.0.0.1"
listen_port = 8080
